[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  'forge-std/=lib/forge-std/src/',
]
verbosity = 3

[ci]
fuzz-runs = 10_000

# See more config options https://github.com/gakonst/foundry/tree/master/config
